// src/lib/mockPatient.js
// Use access code "000000" to load this mock patient in development

export const mockPatient = {
  age: 34,
  shareNotes: true,
  hasActiveSubscription: true,
  previousMedicines: [],

  // Preventive / daily medications
  preventiveMedicines: [
    {
      medicineId: 1,
      reason: "Migrene profylakse",
      dose: "40 mg",
      startedUsage: "2025-09-01",
      stoppedUsage: null,
      medicine: {
        id: 1,
        name: "Propranolol",
        type: 2,
        availableDoses: "40 mg",
        image: null,
      },
    },
  ],

  // Acute / on-demand medications
  medicines: [
    {
      id: 2,
      name: "Ibuprofen",
      atcCode: "M01AE01",
      ingredients: ["IBUPROFEN"],
    },
    {
      id: 3,
      name: "Sumatriptan",
      atcCode: "N02CC01",
      ingredients: ["SUMATRIPTAN"],
    },
    {
      id: 4,
      name: "Paracetamol",
      atcCode: "N02BE01",
      ingredients: ["PARACETAMOL_"],
    },
  ],

  userMedicines: [
    {
      medicineId: 2,
      reason: "Smertestillende ved anfall",
      dose: "400 mg",
      startedUsage: "2024-03-01",
      stoppedUsage: null,
      medicine: {
        id: 2,
        name: "Ibuprofen",
        type: 1,
        availableDoses: "400 mg",
        image: null,
      },
    },
    {
      medicineId: 3,
      reason: "Migrene – ved behov",
      dose: "50 mg",
      startedUsage: "2025-01-10",
      stoppedUsage: null,
      medicine: {
        id: 3,
        name: "Sumatriptan",
        type: 1,
        availableDoses: "50 mg",
        image: null,
      },
    },
    {
      medicineId: 4,
      reason: "Lett hodepine",
      dose: "1000 mg",
      startedUsage: "2024-01-01",
      stoppedUsage: null,
      medicine: {
        id: 4,
        name: "Paracetamol",
        type: 1,
        availableDoses: "1000 mg",
        image: null,
      },
    },
  ],

  // Monthly summary scores (for overview charts)
  scores: {
    "2025-10-01": 4,
    "2025-11-01": 6,
    "2025-12-01": 9,
    "2026-01-01": 7,
    "2026-02-01": 11,
    "2026-03-01": 5,
  },

  questionnaires: [],
  advice: [],

  // Daily records — 26 entries from Oct 2025 → Mar 2026
  records: [
    // ── October 2025 ──────────────────────────────────────────────────────────
    {
      date: "2025-10-03",
      intensity: 2, // headache pain 1-10
      duration: 2, // hours
      headacheType: "tension", // tension | migraine | cluster | other
      location: "bilateral", // bilateral | unilateral_left | unilateral_right | whole_head
      pulsating: false,
      nausea: false,
      vomiting: false,
      lightSensitivity: 1, // 0-3
      soundSensitivity: 1,
      aura: false,
      triggerStress: true,
      triggerSleep: false,
      triggerHormones: false,
      triggerFood: false,
      triggerWeather: false,
      triggerAlcohol: false,
      sleepHours: 7,
      sleepQuality: 3, // 1-5
      stress: 3, // 1-5
      physicalActivity: 60, // minutes
      period: false,
      absentWork: false,
      note: null,
      acuteMedicines: [4],
      acuteMedicinesAtc: ["N02BE01"],
      acuteMedicinesDoses: [1000],
      acuteMedicinesUsedTimes: [1],
    },
    {
      date: "2025-10-09",
      intensity: 4,
      duration: 5,
      headacheType: "tension",
      location: "bilateral",
      pulsating: false,
      nausea: true,
      vomiting: false,
      lightSensitivity: 2,
      soundSensitivity: 2,
      aura: false,
      triggerStress: true,
      triggerSleep: true,
      triggerHormones: false,
      triggerFood: false,
      triggerWeather: false,
      triggerAlcohol: false,
      sleepHours: 5,
      sleepQuality: 2,
      stress: 4,
      physicalActivity: 0,
      period: false,
      absentWork: false,
      note: "Dårlig natt, stressende dag på jobb",
      acuteMedicines: [2],
      acuteMedicinesAtc: ["M01AE01"],
      acuteMedicinesDoses: [400],
      acuteMedicinesUsedTimes: [1],
    },
    {
      date: "2025-10-17",
      intensity: 7,
      duration: 14,
      headacheType: "migraine",
      location: "unilateral_left",
      pulsating: true,
      nausea: true,
      vomiting: true,
      lightSensitivity: 3,
      soundSensitivity: 3,
      aura: true,
      triggerStress: false,
      triggerSleep: false,
      triggerHormones: false,
      triggerFood: true,
      triggerWeather: true,
      triggerAlcohol: false,
      sleepHours: 6,
      sleepQuality: 2,
      stress: 2,
      physicalActivity: 0,
      period: false,
      absentWork: true,
      note: "Klassisk migrene med aura, måtte legge meg",
      acuteMedicines: [3],
      acuteMedicinesAtc: ["N02CC01"],
      acuteMedicinesDoses: [50],
      acuteMedicinesUsedTimes: [2],
    },
    {
      date: "2025-10-24",
      intensity: 2,
      duration: 1,
      headacheType: "tension",
      location: "bilateral",
      pulsating: false,
      nausea: false,
      vomiting: false,
      lightSensitivity: 0,
      soundSensitivity: 0,
      aura: false,
      triggerStress: false,
      triggerSleep: false,
      triggerHormones: false,
      triggerFood: false,
      triggerWeather: false,
      triggerAlcohol: true,
      sleepHours: 8,
      sleepQuality: 4,
      stress: 2,
      physicalActivity: 45,
      period: false,
      absentWork: false,
      note: null,
      acuteMedicines: [4],
      acuteMedicinesAtc: ["N02BE01"],
      acuteMedicinesDoses: [1000],
      acuteMedicinesUsedTimes: [1],
    },

    // ── November 2025 ─────────────────────────────────────────────────────────
    {
      date: "2025-11-02",
      intensity: 3,
      duration: 3,
      headacheType: "tension",
      location: "bilateral",
      pulsating: false,
      nausea: false,
      vomiting: false,
      lightSensitivity: 1,
      soundSensitivity: 1,
      aura: false,
      triggerStress: true,
      triggerSleep: false,
      triggerHormones: false,
      triggerFood: false,
      triggerWeather: false,
      triggerAlcohol: false,
      sleepHours: 7,
      sleepQuality: 3,
      stress: 3,
      physicalActivity: 30,
      period: false,
      absentWork: false,
      note: null,
      acuteMedicines: [4],
      acuteMedicinesAtc: ["N02BE01"],
      acuteMedicinesDoses: [1000],
      acuteMedicinesUsedTimes: [1],
    },
    {
      date: "2025-11-07",
      intensity: 6,
      duration: 10,
      headacheType: "migraine",
      location: "unilateral_right",
      pulsating: true,
      nausea: true,
      vomiting: false,
      lightSensitivity: 3,
      soundSensitivity: 2,
      aura: false,
      triggerStress: true,
      triggerSleep: true,
      triggerHormones: false,
      triggerFood: false,
      triggerWeather: false,
      triggerAlcohol: false,
      sleepHours: 5,
      sleepQuality: 1,
      stress: 5,
      physicalActivity: 0,
      period: false,
      absentWork: true,
      note: "Ekstremt stressende uke, sovet for lite",
      acuteMedicines: [3],
      acuteMedicinesAtc: ["N02CC01"],
      acuteMedicinesDoses: [50],
      acuteMedicinesUsedTimes: [1],
    },
    {
      date: "2025-11-14",
      intensity: 3,
      duration: 4,
      headacheType: "tension",
      location: "bilateral",
      pulsating: false,
      nausea: false,
      vomiting: false,
      lightSensitivity: 1,
      soundSensitivity: 1,
      aura: false,
      triggerStress: false,
      triggerSleep: false,
      triggerHormones: true,
      triggerFood: false,
      triggerWeather: false,
      triggerAlcohol: false,
      sleepHours: 7,
      sleepQuality: 3,
      stress: 2,
      physicalActivity: 60,
      period: true,
      absentWork: false,
      note: null,
      acuteMedicines: [2],
      acuteMedicinesAtc: ["M01AE01"],
      acuteMedicinesDoses: [400],
      acuteMedicinesUsedTimes: [2],
    },
    {
      date: "2025-11-21",
      intensity: 5,
      duration: 8,
      headacheType: "migraine",
      location: "unilateral_left",
      pulsating: true,
      nausea: true,
      vomiting: false,
      lightSensitivity: 3,
      soundSensitivity: 3,
      aura: true,
      triggerStress: false,
      triggerSleep: false,
      triggerHormones: true,
      triggerFood: false,
      triggerWeather: true,
      triggerAlcohol: false,
      sleepHours: 6,
      sleepQuality: 2,
      stress: 2,
      physicalActivity: 0,
      period: true,
      absentWork: false,
      note: "Menstruasjonsmigrene",
      acuteMedicines: [3],
      acuteMedicinesAtc: ["N02CC01"],
      acuteMedicinesDoses: [50],
      acuteMedicinesUsedTimes: [2],
    },
    {
      date: "2025-11-28",
      intensity: 4,
      duration: 5,
      headacheType: "tension",
      location: "bilateral",
      pulsating: false,
      nausea: false,
      vomiting: false,
      lightSensitivity: 1,
      soundSensitivity: 1,
      aura: false,
      triggerStress: false,
      triggerSleep: false,
      triggerHormones: false,
      triggerFood: false,
      triggerWeather: true,
      triggerAlcohol: false,
      sleepHours: 7,
      sleepQuality: 3,
      stress: 2,
      physicalActivity: 30,
      period: false,
      absentWork: false,
      note: null,
      acuteMedicines: [4],
      acuteMedicinesAtc: ["N02BE01"],
      acuteMedicinesDoses: [1000],
      acuteMedicinesUsedTimes: [1],
    },

    // ── December 2025 ─────────────────────────────────────────────────────────
    {
      date: "2025-12-02",
      intensity: 5,
      duration: 6,
      headacheType: "migraine",
      location: "unilateral_left",
      pulsating: true,
      nausea: true,
      vomiting: false,
      lightSensitivity: 2,
      soundSensitivity: 2,
      aura: false,
      triggerStress: true,
      triggerSleep: false,
      triggerHormones: false,
      triggerFood: true,
      triggerWeather: false,
      triggerAlcohol: true,
      sleepHours: 6,
      sleepQuality: 2,
      stress: 3,
      physicalActivity: 0,
      period: false,
      absentWork: false,
      note: "Julebord kvelden før",
      acuteMedicines: [3, 4],
      acuteMedicinesAtc: ["N02CC01", "N02BE01"],
      acuteMedicinesDoses: [50, 1000],
      acuteMedicinesUsedTimes: [1, 1],
    },
    {
      date: "2025-12-09",
      intensity: 3,
      duration: 3,
      headacheType: "tension",
      location: "bilateral",
      pulsating: false,
      nausea: false,
      vomiting: false,
      lightSensitivity: 1,
      soundSensitivity: 0,
      aura: false,
      triggerStress: true,
      triggerSleep: false,
      triggerHormones: false,
      triggerFood: false,
      triggerWeather: false,
      triggerAlcohol: false,
      sleepHours: 7,
      sleepQuality: 3,
      stress: 4,
      physicalActivity: 45,
      period: false,
      absentWork: false,
      note: null,
      acuteMedicines: [4],
      acuteMedicinesAtc: ["N02BE01"],
      acuteMedicinesDoses: [1000],
      acuteMedicinesUsedTimes: [1],
    },
    {
      date: "2025-12-15",
      intensity: 8,
      duration: 20,
      headacheType: "migraine",
      location: "unilateral_left",
      pulsating: true,
      nausea: true,
      vomiting: true,
      lightSensitivity: 3,
      soundSensitivity: 3,
      aura: true,
      triggerStress: true,
      triggerSleep: true,
      triggerHormones: false,
      triggerFood: false,
      triggerWeather: false,
      triggerAlcohol: false,
      sleepHours: 4,
      sleepQuality: 1,
      stress: 5,
      physicalActivity: 0,
      period: false,
      absentWork: true,
      note: "Verste anfallet på lenge, varte nesten et helt døgn",
      acuteMedicines: [3],
      acuteMedicinesAtc: ["N02CC01"],
      acuteMedicinesDoses: [50],
      acuteMedicinesUsedTimes: [2],
    },
    {
      date: "2025-12-19",
      intensity: 4,
      duration: 5,
      headacheType: "tension",
      location: "bilateral",
      pulsating: false,
      nausea: false,
      vomiting: false,
      lightSensitivity: 1,
      soundSensitivity: 1,
      aura: false,
      triggerStress: false,
      triggerSleep: false,
      triggerHormones: false,
      triggerFood: false,
      triggerWeather: true,
      triggerAlcohol: false,
      sleepHours: 8,
      sleepQuality: 4,
      stress: 2,
      physicalActivity: 60,
      period: false,
      absentWork: false,
      note: null,
      acuteMedicines: [2],
      acuteMedicinesAtc: ["M01AE01"],
      acuteMedicinesDoses: [400],
      acuteMedicinesUsedTimes: [1],
    },
    {
      date: "2025-12-24",
      intensity: 3,
      duration: 2,
      headacheType: "tension",
      location: "bilateral",
      pulsating: false,
      nausea: false,
      vomiting: false,
      lightSensitivity: 0,
      soundSensitivity: 0,
      aura: false,
      triggerStress: false,
      triggerSleep: false,
      triggerHormones: false,
      triggerFood: false,
      triggerWeather: false,
      triggerAlcohol: true,
      sleepHours: 9,
      sleepQuality: 4,
      stress: 1,
      physicalActivity: 30,
      period: false,
      absentWork: false,
      note: "Julaften, litt rødvin",
      acuteMedicines: [4],
      acuteMedicinesAtc: ["N02BE01"],
      acuteMedicinesDoses: [1000],
      acuteMedicinesUsedTimes: [1],
    },

    // ── January 2026 ──────────────────────────────────────────────────────────
    {
      date: "2026-01-04",
      intensity: 3,
      duration: 3,
      headacheType: "tension",
      location: "bilateral",
      pulsating: false,
      nausea: false,
      vomiting: false,
      lightSensitivity: 1,
      soundSensitivity: 1,
      aura: false,
      triggerStress: true,
      triggerSleep: false,
      triggerHormones: false,
      triggerFood: false,
      triggerWeather: false,
      triggerAlcohol: false,
      sleepHours: 7,
      sleepQuality: 3,
      stress: 3,
      physicalActivity: 30,
      period: false,
      absentWork: false,
      note: "Tilbake på jobb etter ferien",
      acuteMedicines: [4],
      acuteMedicinesAtc: ["N02BE01"],
      acuteMedicinesDoses: [1000],
      acuteMedicinesUsedTimes: [1],
    },
    {
      date: "2026-01-11",
      intensity: 5,
      duration: 8,
      headacheType: "migraine",
      location: "unilateral_right",
      pulsating: true,
      nausea: true,
      vomiting: false,
      lightSensitivity: 2,
      soundSensitivity: 2,
      aura: false,
      triggerStress: false,
      triggerSleep: true,
      triggerHormones: false,
      triggerFood: false,
      triggerWeather: false,
      triggerAlcohol: false,
      sleepHours: 5,
      sleepQuality: 2,
      stress: 3,
      physicalActivity: 0,
      period: false,
      absentWork: false,
      note: null,
      acuteMedicines: [3],
      acuteMedicinesAtc: ["N02CC01"],
      acuteMedicinesDoses: [50],
      acuteMedicinesUsedTimes: [1],
    },
    {
      date: "2026-01-18",
      intensity: 2,
      duration: 2,
      headacheType: "tension",
      location: "bilateral",
      pulsating: false,
      nausea: false,
      vomiting: false,
      lightSensitivity: 0,
      soundSensitivity: 0,
      aura: false,
      triggerStress: false,
      triggerSleep: false,
      triggerHormones: false,
      triggerFood: false,
      triggerWeather: false,
      triggerAlcohol: false,
      sleepHours: 8,
      sleepQuality: 4,
      stress: 2,
      physicalActivity: 60,
      period: false,
      absentWork: false,
      note: null,
      acuteMedicines: [],
      acuteMedicinesAtc: [],
      acuteMedicinesDoses: [],
      acuteMedicinesUsedTimes: [],
    },
    {
      date: "2026-01-25",
      intensity: 6,
      duration: 12,
      headacheType: "migraine",
      location: "unilateral_left",
      pulsating: true,
      nausea: true,
      vomiting: true,
      lightSensitivity: 3,
      soundSensitivity: 3,
      aura: true,
      triggerStress: false,
      triggerSleep: false,
      triggerHormones: true,
      triggerFood: false,
      triggerWeather: true,
      triggerAlcohol: false,
      sleepHours: 6,
      sleepQuality: 2,
      stress: 2,
      physicalActivity: 0,
      period: true,
      absentWork: true,
      note: "Menstruasjonsmigrene igjen",
      acuteMedicines: [3],
      acuteMedicinesAtc: ["N02CC01"],
      acuteMedicinesDoses: [50],
      acuteMedicinesUsedTimes: [2],
    },

    // ── February 2026 ─────────────────────────────────────────────────────────
    {
      date: "2026-02-03",
      intensity: 7,
      duration: 16,
      headacheType: "migraine",
      location: "unilateral_left",
      pulsating: true,
      nausea: true,
      vomiting: true,
      lightSensitivity: 3,
      soundSensitivity: 3,
      aura: true,
      triggerStress: true,
      triggerSleep: true,
      triggerHormones: false,
      triggerFood: false,
      triggerWeather: false,
      triggerAlcohol: false,
      sleepHours: 4,
      sleepQuality: 1,
      stress: 5,
      physicalActivity: 0,
      period: false,
      absentWork: true,
      note: "Veldig hardt anfall, måtte be noen hente barna",
      acuteMedicines: [3],
      acuteMedicinesAtc: ["N02CC01"],
      acuteMedicinesDoses: [50],
      acuteMedicinesUsedTimes: [2],
    },
    {
      date: "2026-02-10",
      intensity: 4,
      duration: 5,
      headacheType: "tension",
      location: "bilateral",
      pulsating: false,
      nausea: false,
      vomiting: false,
      lightSensitivity: 1,
      soundSensitivity: 1,
      aura: false,
      triggerStress: true,
      triggerSleep: false,
      triggerHormones: false,
      triggerFood: false,
      triggerWeather: false,
      triggerAlcohol: false,
      sleepHours: 7,
      sleepQuality: 3,
      stress: 4,
      physicalActivity: 30,
      period: false,
      absentWork: false,
      note: null,
      acuteMedicines: [2],
      acuteMedicinesAtc: ["M01AE01"],
      acuteMedicinesDoses: [400],
      acuteMedicinesUsedTimes: [2],
    },
    {
      date: "2026-02-14",
      intensity: 3,
      duration: 3,
      headacheType: "tension",
      location: "bilateral",
      pulsating: false,
      nausea: false,
      vomiting: false,
      lightSensitivity: 0,
      soundSensitivity: 0,
      aura: false,
      triggerStress: false,
      triggerSleep: false,
      triggerHormones: false,
      triggerFood: false,
      triggerWeather: false,
      triggerAlcohol: false,
      sleepHours: 8,
      sleepQuality: 4,
      stress: 2,
      physicalActivity: 45,
      period: false,
      absentWork: false,
      note: null,
      acuteMedicines: [4],
      acuteMedicinesAtc: ["N02BE01"],
      acuteMedicinesDoses: [1000],
      acuteMedicinesUsedTimes: [1],
    },
    {
      date: "2026-02-22",
      intensity: 5,
      duration: 9,
      headacheType: "migraine",
      location: "unilateral_left",
      pulsating: true,
      nausea: true,
      vomiting: false,
      lightSensitivity: 2,
      soundSensitivity: 2,
      aura: false,
      triggerStress: false,
      triggerSleep: false,
      triggerHormones: true,
      triggerFood: false,
      triggerWeather: false,
      triggerAlcohol: false,
      sleepHours: 7,
      sleepQuality: 2,
      stress: 2,
      physicalActivity: 0,
      period: true,
      absentWork: false,
      note: "Menstruasjonshodepine",
      acuteMedicines: [3],
      acuteMedicinesAtc: ["N02CC01"],
      acuteMedicinesDoses: [50],
      acuteMedicinesUsedTimes: [1],
    },

    // ── March 2026 ────────────────────────────────────────────────────────────
    {
      date: "2026-03-03",
      intensity: 2,
      duration: 2,
      headacheType: "tension",
      location: "bilateral",
      pulsating: false,
      nausea: false,
      vomiting: false,
      lightSensitivity: 0,
      soundSensitivity: 0,
      aura: false,
      triggerStress: false,
      triggerSleep: false,
      triggerHormones: false,
      triggerFood: false,
      triggerWeather: false,
      triggerAlcohol: false,
      sleepHours: 8,
      sleepQuality: 5,
      stress: 1,
      physicalActivity: 90,
      period: false,
      absentWork: false,
      note: null,
      acuteMedicines: [],
      acuteMedicinesAtc: [],
      acuteMedicinesDoses: [],
      acuteMedicinesUsedTimes: [],
    },
    {
      date: "2026-03-10",
      intensity: 4,
      duration: 4,
      headacheType: "tension",
      location: "bilateral",
      pulsating: false,
      nausea: false,
      vomiting: false,
      lightSensitivity: 1,
      soundSensitivity: 1,
      aura: false,
      triggerStress: true,
      triggerSleep: false,
      triggerHormones: false,
      triggerFood: false,
      triggerWeather: true,
      triggerAlcohol: false,
      sleepHours: 7,
      sleepQuality: 3,
      stress: 3,
      physicalActivity: 30,
      period: false,
      absentWork: false,
      note: "Værskifte",
      acuteMedicines: [4],
      acuteMedicinesAtc: ["N02BE01"],
      acuteMedicinesDoses: [1000],
      acuteMedicinesUsedTimes: [1],
    },
    {
      date: "2026-03-17",
      intensity: 3,
      duration: 2,
      headacheType: "tension",
      location: "bilateral",
      pulsating: false,
      nausea: false,
      vomiting: false,
      lightSensitivity: 0,
      soundSensitivity: 0,
      aura: false,
      triggerStress: false,
      triggerSleep: false,
      triggerHormones: false,
      triggerFood: false,
      triggerWeather: false,
      triggerAlcohol: false,
      sleepHours: 8,
      sleepQuality: 4,
      stress: 2,
      physicalActivity: 60,
      period: false,
      absentWork: false,
      note: null,
      acuteMedicines: [4],
      acuteMedicinesAtc: ["N02BE01"],
      acuteMedicinesDoses: [1000],
      acuteMedicinesUsedTimes: [1],
    },
    {
      date: "2026-03-24",
      intensity: 2,
      duration: 1,
      headacheType: "tension",
      location: "bilateral",
      pulsating: false,
      nausea: false,
      vomiting: false,
      lightSensitivity: 0,
      soundSensitivity: 0,
      aura: false,
      triggerStress: false,
      triggerSleep: false,
      triggerHormones: false,
      triggerFood: false,
      triggerWeather: false,
      triggerAlcohol: false,
      sleepHours: 9,
      sleepQuality: 5,
      stress: 1,
      physicalActivity: 90,
      period: false,
      absentWork: false,
      note: "God uke, nesten ingen hodepine",
      acuteMedicines: [],
      acuteMedicinesAtc: [],
      acuteMedicinesDoses: [],
      acuteMedicinesUsedTimes: [],
    },
  ],
};
